#!/usr/bin/env bash

#pgcontents init -l $DATABASE_URL --no-prompt

# HACK: run install for nbextensions
/app/.conda/bin/pip install git+git://github.com/ipython-contrib/IPython-notebook-extensions.git
#conda install -c jochym nbextensions=master

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	--config=jupyterconfig.py \
	notebooks
